return {
    "php-debug-adapter",
    "js-debug-adapter",
    "codelldb",
    "phpcs",
    "phpstan",
    --[[
    "docker-compose-language-service",
    "emmet-ls",
    "lua-language-server",
    "phpactor",
    "phpcbf",
    "phpcs",
    "php-cs-fixer",
    "phpstan",
    "prettier",
    "stylua",
    "tailwindcss-language-server",
    "typescript-language-server"
    ]]
}
